# Generated by Django 3.2.15 on 2022-09-28 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaf',
            name='id_m',
            field=models.PositiveIntegerField(auto_created=True, verbose_name='Уникальный ID'),
        ),
    ]
