# Generated by Django 3.2.15 on 2022-09-28 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0002_alter_leaf_id_m'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaf',
            name='id_m',
            field=models.PositiveIntegerField(auto_created=True, unique=True, verbose_name='Уникальный ID'),
        ),
    ]
