# Generated by Django 3.2.15 on 2022-09-29 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0004_remove_leaf_id_m'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bearing',
            options={'verbose_name': 'Подшипник', 'verbose_name_plural': 'Подшипники'},
        ),
    ]
