# Generated by Django 3.2.15 on 2022-09-30 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0006_bearing_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bearing',
            name='photo',
            field=models.ImageField(null=True, upload_to='images', verbose_name='Картинка'),
        ),
    ]
