# Generated by Django 3.2.15 on 2022-10-03 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0007_alter_bearing_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bearing2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название/Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('photo', models.ImageField(null=True, upload_to='images', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Подшипник2',
                'verbose_name_plural': 'Подшипники2',
            },
        ),
    ]
